# Generated by fusen: do not edit by hand

test_that("cranology works", {
  result <- cranology("2020-03-15")
  # generated with dput()
  expected_df <- structure(
    list(date = "2020-03-15", n = 15367L),
    class = "data.frame",
    row.names = c(NA, -1L)
  )
  expect_equal(result, expected_df)
})
